version: '3.8'

services:
  app1:
    build:
      context: "8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - backend

  app2:
    build:
      context: "8001"
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    networks:
      - backend

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - backend
    depends_on:
      - app1
      - app2

  mongo:
    hostname: mongo
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "db-data:/mask/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge